version: '3'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  script:
    build: ./script
    restart: on-failure
    depends_on:
      - mysql
    env_file:
      - .env
  adminer:
    image: adminer
    ports:
      - 8080:8080